export const CACHE_KEYS = {
  materiList: (page: number, isPremium: boolean) => `materi:list:page:${page}:premium:${isPremium}`,
  materiListByKelas: (kelas: string, isPremium: boolean, tipe?: 'TEKS' | 'VIDEO') => `materi:list:kelas:${kelas}:premium:${isPremium}:tipe:${tipe || 'all'}`,
  materiDetail: (slug: string) => `materi:detail:${slug}`,
  materiCount: () => `materi:count:published`,
  quizList: (page: number, isPremium: boolean) => `quiz:list:page:${page}:premium:${isPremium}`,
  quizDetail: (id: string) => `quiz:detail:${id}`,
  quizCount: () => `quiz:count:published`,
  packageList: () => `package:list`,
  adminStats: () => `admin:stats`,
  tugasList: (page: number, isPremium: boolean, kelas?: string) => `tugas:list:page:${page}:premium:${isPremium}:kelas:${kelas || 'all'}`,
  tugasListByKelas: (kelas: string, isPremium: boolean) => `tugas:list:kelas:${kelas}:premium:${isPremium}`,
  tugasDetail: (slug: string) => `tugas:detail:${slug}`,
  userQuizAttempts: (userId: string) => `user:${userId}:quiz:attempts`,
  userTugasSubmissions: (userId: string) => `user:${userId}:tugas:submissions`,
  userMateriProgress: (userId: string) => `user:${userId}:materi:progress`,
};
